In [ ]:
import numpy as np


# np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# a1= np.linspace(0, 20, 6)
# print(a1)
# a2= np.arange(0, 20)
# a2[2:7]
# a2[a2<10]

#print(a2[2:7])

# m1 = np.matrix([[1,4,9,121,144,169],
#                 [16,25,36,196,225,256],
#                 [49,64,81,289,324,361]])

# np.save('m1.npy', m1)
# m1 = np.load('m1.npy')

# # Calculate the average of the matrix m1
# average_m1 = np.mean(m1)
# print("Average of m1:", average_m1)
# np.cos([0,1,3,4,5])

# b1=np.array([1,2,3,5,8])
# b2=np.array([0,3,4,2,1]) 
# c1 = b1 + b2
# print(c1)   
# c2 = c1*b1
# print(c2[2])   

# l1=[1,2,3,4,5]
# l2=[6,7,8,9,10]
# c2= l1+l2
# print(c2)
# d1 = np.array([[9,8,7], [6,5,4], [3,2,1]])
# # print(d1)
# np.save('d1.npy',d1)

# d1 = np.load('d1.npy')
# d1[1]=5
# print(d1)
#np.ones([2,2])
#np.load('d1.npy')


# n1= np.matrix([[121,144,169],[196,225,256],[289,324,361]])
# n2= np.matrix([[1,4,9],[1,5,4],[9,4,8]])

# n3 = n1*n2
# print(n3)



[[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]
