In [ ]:
import numpy as np
import pandas as pd

ar= ["absolute", 'absolute_import', 'all']
ar1=[ 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'array', 'array2string', 'array_equal']
n_ar = np.array([ar,ar,ar])


x = np.arange(10,20,3)

print (x)
x=  np.linspace(10,20,5)
print ("linspace",x)

x= np.zeros((2,3))

# np.ones((3,4)) 
# #np.empty((2,3)) 
# np.full((2,2),4)
# np.eye(3,3)

print (x) 



UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U15'), dtype('<U15')) -> None

In [5]:
# x= np.arange(1,5).reshape(2,2)
# x1 = np.eye(2)

np.random.seed(99)  # Set the seed for reproducibility
z = np.random.rand(2,3)
print(z)

z2 = np.random.randn(7,7)
print (z2[0:1,1:3])

z2[0:1,1:3]= [.77777,.88888]
print (z2[0:1,1:3])
z2
print(z2.min(axis=1))
print(np.min(z2, axis=1))
print(np.max(z2, axis=1))




[[0.67227856 0.4880784  0.82549517]
 [0.03144639 0.80804996 0.56561742]]
[[-0.06903086  0.75518049]]
[[0.77777 0.88888]]
[-2.36783759 -1.43500814 -0.85579558 -0.8164661  -2.13970379 -1.19193417
 -0.97467528]
[-2.36783759 -1.43500814 -0.85579558 -0.8164661  -2.13970379 -1.19193417
 -0.97467528]
[0.88888    0.88281715 0.59095329 0.92595278 2.20731059 1.76347792
 1.08622556]


In [28]:
#m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m = np.arange(1,10).reshape(3,3)
m[0:2,1:2] = 0
print (m)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [22]:
m1 = np.arange(1,15)
#np.save(r'D:\0-AI-ML\ai-ml\week2\m1.npy', m1)  # Save the array to a file
np.save('D:\\0-AI-ML\\ai-ml\\week2\\m1.npy', m1)  # Save the array to a file
np.savetxt('D:\\0-AI-ML\\ai-ml\\week2\\m1.txt', m1)  # Save the array to a text file
np.savez('D:\\0-AI-ML\\ai-ml\\week2\\m12.npy', m1)  # Save the array to a file
m5 = np.load('D:\\0-AI-ML\\ai-ml\\week2\\m1.npy')  # Load the array from the file
print(m5)
m6 = np.loadtxt('D:\\0-AI-ML\\ai-ml\\week2\\m1.txt')  # Load the array from the text file
m6

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

In [ ]:
n1 = np.full((3,5),3)
n2 = np.copy(n1)



array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])