In [ ]:
import numpy as np

ar= ["absolute", 'absolute_import', 'all']
ar1=[ 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'array', 'array2string', 'array_equal']
n_ar = np.array([ar,ar,ar])

x = np.arange(10,20,3)

print (x)
x=  np.linspace(10,20,3)
print (x)

x= np.zeros((2,3))

# np.ones((3,4)) 
# #np.empty((2,3)) 
# np.full((2,2),4)
# np.eye(3,3)

print (x) 



[10 13 16 19]
[10. 15. 20.]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
x= np.arange(0,10)
print (x)
y = x.resize((2,3))
print (x)
print ("this is Y",y)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]]
this is Y None
